#

[asciinema]
secure = ["ASCIINEMA_API_TOKEN"]

[danger]
secure = ["DANGER_GITHUB_API_TOKEN"]

[nimble]
secure = ["NIMBLE_GITHUB_API_TOKEN"]

[brew]
secure = ["HOMEBREW_GITHUB_API_TOKEN"]
remove = ["GIT_CONFIG"]
  [brew.additional]
  HOMEBREW_INSTALL_BADGE = "ðŸŒˆ"
  HOMEBREW_VERBOSE = true
  HOMEBREW_NO_INSECURE_REDIRECT = true

[gistit]
secure = ["GISTIT_TOKEN"]

[pass]
  [pass.additional]
  PASSWORD_STORE_ENABLE_EXTENSIONS = true

[http]
  [http.additional]
  HTTPIE_CONFIG_DIR = "/Users/Samantha/.config/httpie/"

[notmuch]
  [notmuch.additional]
  NOTMUCH_CONFIG = "/Users/Samantha/.config/notmuch/notmuch-config"

[alot]
  [alot.additional]
  NOTMUCH_CONFIG = "/Users/Samantha/.config/notmuch/notmuch-config"

[weechat]
secure = ["WEECHAT_PASSPHRASE"]
  [weechat.additional]
  WEECHAT_HOME = "/Users/Samantha/.config/weechat/"

[omni]
secure = ["OMNI_SYNC_MAILDROP_ADDR"]

[hub]
secure = ["GITHUB_TOKEN"]
